In [1]:
price = [2.0,1.0,10.0]
type(price)

list

In [2]:
quantity_sold = [17.0,40.0,1.0]
type(quantity_sold)

list

In [3]:
#price * quantity_sold

In [4]:
import numpy as np
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [5]:
price_array * quantity_sold_array

array([34., 40., 10.])

In [6]:
cost = [0.25,0.5,5.0]
cost_arrary = np.array(cost)

In [7]:
profit_array = price_array - cost_arrary
print(profit_array)

[1.75 0.5  5.  ]


In [8]:
profit_array > 2.00

array([False, False,  True])

In [9]:
price_array = price_array + 7
print(price_array)

[ 9.  8. 17.]


In [10]:
#just fixing the mistake
price_array = price_array - 7
#The proper way to append an element to an array
price_array = np.append(price_array, 7)
print(price_array)

[ 2.  1. 10.  7.]


In [11]:
price_array = np.append(price_array,[4.5,3,4,9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [12]:
print(price_array.dtype)

float64


In [13]:
#deleting an item in the numpy array
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [14]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


In [15]:
#Added column names for items to make it easier to visualize
items = ["brownie","cookie","cake","pie","fudge","cupcake","banana bread"]
items_array = np.array(items)
print(items_array)

['brownie' 'cookie' 'cake' 'pie' 'fudge' 'cupcake' 'banana bread']


In [16]:
#Task 2) Adding the quantities sold for the newest items added; pie, fudge, cupcake and banana bread
print('current quantity before adding: ',quantity_sold_array)
quantity_sold_array = np.append(quantity_sold_array,[2,3,16,5])
print('latest quantity after adding',quantity_sold_array)

current quantity before adding:  [17. 40.  1.]
latest quantity after adding [17. 40.  1.  2.  3. 16.  5.]


In [17]:
#Task 2 contd.) Update quantities sold of cookies from 40 to 39, since one fell and was not actually sold
print('quantity sold before update: ',quantity_sold_array)
quantity_sold_array[1] = quantity_sold_array[1]-1
print('quantity sold after update: ', quantity_sold_array)

quantity sold before update:  [17. 40.  1.  2.  3. 16.  5.]
quantity sold after update:  [17. 39.  1.  2.  3. 16.  5.]


In [18]:
#Task 3) Determine the amount of money collected for each item
print('Array of prices for each item: ',price_array)
print('Array of quantities sold for each item: ',quantity_sold_array)
money_collected_array = price_array * quantity_sold_array
print('Array of money collected for each item: ',money_collected_array)
print('Total amount of money collected: ',money_collected_array.sum())

Array of prices for each item:  [ 2.   1.  12.   7.   4.5  3.   4. ]
Array of quantities sold for each item:  [17. 39.  1.  2.  3. 16.  5.]
Array of money collected for each item:  [34.  39.  12.  14.  13.5 48.  20. ]
Total amount of money collected:  180.5


In [19]:
#Task 4) Create a Numpy array of the quantities remaining
#Adding zero for the sold out items ensures that bake club arrays have the same dimension size/length across all arrays
quantity_leftover_array = np.array([0,0,2,1,6,0,2])
print('Array of quantities leftover for each item: ', quantity_leftover_array)

Array of quantities leftover for each item:  [0 0 2 1 6 0 2]


In [20]:
#Task 5) Determine how much was collected from clearance sale; with all prices cut in half
price_array_clearance1 = price_array/2
print('Array of prices on clearance: ',price_array_clearance1)
money_collected_clearance1_array = price_array_clearance1 * quantity_leftover_array
print('Array of money collected from clearance: ', money_collected_clearance1_array)
print('Total amount of money collected from clearance', money_collected_clearance1_array.sum())

Array of prices on clearance:  [1.   0.5  6.   3.5  2.25 1.5  2.  ]
Array of money collected from clearance:  [ 0.   0.  12.   3.5 13.5  0.   4. ]
Total amount of money collected from clearance 33.0


In [21]:
#Task 6) Determine the grand total amount collected between the regular and clearance sales
grand_total_collected = money_collected_array+money_collected_clearance1_array
print('Grand total collected is: ', grand_total_collected.sum())

Grand total collected is:  213.5
