In [44]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [45]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [46]:
filepath = '/content/drive/Othercomputers/My Laptop/data-science-assignments/07 - Logistic Regression Regularization/'
filename = 'titanic.csv'
filepathname = filepath + filename

In [47]:
df = pd.read_csv(filepathname)
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [48]:
feature_cols = ['Pclass', 'Parch', 'Age', 'Sex']
#Transform Sex column, so model can use it
df.replace({'Sex': {'male':0,'female':1}},inplace=True)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    int64  
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB


In [50]:
#Remove rows where age is nan from the dataset
df = df.loc[~df['Age'].isnull(), :]

#Creating features matrix and target vector
X = df.loc[:, feature_cols]
y = df['Survived']

In [51]:
#Splitting data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

In [52]:
#Instantiate an instance of StandardScaler
scaler = StandardScaler()
#Fit Only on Training Set
scaler.fit(X_train, y_train)

StandardScaler()

In [53]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [54]:
#Instantiate an instance of a model
logreg = LogisticRegression()
#Train the model on the data
logreg.fit(X_train, y_train)

LogisticRegression()

In [55]:
predictions = logreg.predict(X_test)

In [56]:
#Ignoring for now
score = logreg.score(X_test, y_test)
print(score)

0.8156424581005587


# Showing Confusion Matrix

In [57]:
# actual values, what the model should predict
y_test.values

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0])

In [58]:
# values that the algorithm predicted
predictions

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0])

In [59]:
# actual values: y_test.values
# model's predictions: predictions
cm = metrics.confusion_matrix(y_test.values, predictions)

In [60]:
cm

array([[87, 16],
       [17, 59]])

In [61]:
cm.shape

(2, 2)

In [62]:
cm.ravel()

array([87, 16, 17, 59])

In [63]:
cm.ravel().shape

(4,)

In [64]:
tn, fp, fn, tp = cm.ravel()

In [65]:
print("True Negatives; Did not survive and model correctly predicted did not survive:",tn)
print("False Positives; Did not survive and model incorrectly predicted that they survive:",fp)
print("False Negatives; Did survive and model incorrectly predicted that they did not survive:",fn)
print("True Positives; Did survive and model correctly predicted that they did survive:",tp)

True Negatives; Did not survive and model correctly predicted did not survive: 87
False Positives; Did not survive and model incorrectly predicted that they survive: 16
False Negatives; Did survive and model incorrectly predicted that they did not survive: 17
True Positives; Did survive and model correctly predicted that they did survive: 59
